### ISSUE TITLE
tab=stars必须作为第一个查询参数，否则不生效

### ISSUE THREAD

**Issue by liuxinqiong** [hanzichi/github-remarks#1]
个人觉得这是个很实用的工具，反馈我碰到的小bug，如果点击下一页的话，扩展就不生效了，因为github此时查询参数为page=2&tab=stars，手动改成tab=stars&page=2生效。

**Comment by lessfish** [comment]
@liuxinqiong  感谢反馈，一个正则没照顾到，已修复
