### ISSUE TITLE
一些改进意见

### ISSUE THREAD

**Issue by MuYunyun** [hanzichi/github-remarks#2]
* 在当前 repo 中没有显示 `增加我的备注`, star 界面是有的
![image](https://user-images.githubusercontent.com/19354791/45605554-65b0f700-ba70-11e8-9e9d-bb003dc35cd9.png)

* 如果能在搜索栏搜索出的项目后面将备注信息带上那就更方便了
![image](https://user-images.githubusercontent.com/19354791/45605505-02bf6000-ba70-11e8-9e05-d179ae93265f.png)

* 考虑移除 jquery

**Comment by lessfish** [comment]
该项目并不是一个好的解决方案，建议使用 [AnyStars](https://github.com/anystars)

**Comment by MuYunyun** [comment]
不过两套方案都有优缺点吧。
谷歌插件这种方案的优点是不用部署数据库，缺点是页面要是改动的话，插件也要同步进行升级。
用 workflow 的这套方案很赞，缺点就是要额外部署，优点是使用起来这种方案更加便利。

**Comment by MuYunyun** [comment]
@hanzichi 提了个 [pr](https://github.com/hanzichi/github-remarks/pull/3)，希望采纳
